#pragma once

#include "MeanLeanWindows.h"
#include <GL/gl.h>
#include <gl/glext.h>
#include <gl/glcorearb.h>
#include <MMSystem.h>


#define DEFINE_GL_FUNC(type, name) type name;
#define DECLARE_GL_FUNC(type, name) extern type name;

DECLARE_GL_FUNC(PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation);
DECLARE_GL_FUNC(PFNGLUNIFORM1FPROC, glUniform1f);
DECLARE_GL_FUNC(PFNGLUNIFORM2FPROC, glUniform2f);
DECLARE_GL_FUNC(PFNGLCREATESHADERPROGRAMEXTPROC, glCreateShaderProgramEXT);
DECLARE_GL_FUNC(PFNGLGETSHADERIVPROC, glGetShaderiv);
DECLARE_GL_FUNC(PFNGLUSEPROGRAMPROC, glUseProgram);
DECLARE_GL_FUNC(PFNGLLINKPROGRAMPROC, glLinkProgram);
DECLARE_GL_FUNC(PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog);
DECLARE_GL_FUNC(PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog);
DECLARE_GL_FUNC(PFNGLCREATESHADERPROC, glCreateShader);
DECLARE_GL_FUNC(PFNGLSHADERSOURCEPROC, glShaderSource);
DECLARE_GL_FUNC(PFNGLCOMPILESHADERPROC, glCompileShader);
DECLARE_GL_FUNC(PFNGLCREATEPROGRAMPROC, glCreateProgram);
DECLARE_GL_FUNC(PFNGLATTACHSHADERPROC, glAttachShader);
DECLARE_GL_FUNC(PFNGLGETPROGRAMIVPROC, glGetProgramiv);
DECLARE_GL_FUNC(PFNGLUNIFORM2FVPROC, glUniform2fv);
DECLARE_GL_FUNC(PFNGLUNIFORM1IPROC, glUniform1i);


//DECLARE_GL_FUNC(PFNGLENABLEPROC, glEnable);
DECLARE_GL_FUNC(PFNGLGENFRAMEBUFFERSPROC, glGenFramebuffers);
DECLARE_GL_FUNC(PFNGLBINDFRAMEBUFFERPROC, glBindFramebuffer);
//DECLARE_GL_FUNC(PFNGLGENTEXTURESEXTPROC, glGenTextures);
//DECLARE_GL_FUNC(PFNGLBINDTEXTUREEXTPROC, glBindTexture);
//DECLARE_GL_FUNC(PFNGLTEXIMAGE2DPROC, glTexImage2D);
//DECLARE_GL_FUNC(PFNGLTEXPARAMETERIPROC, glTexParameteri);
DECLARE_GL_FUNC(PFNGLCHECKFRAMEBUFFERSTATUSPROC, glCheckFramebufferStatus);
DECLARE_GL_FUNC(PFNGLFRAMEBUFFERTEXTUREPROC, glFramebufferTexture);
DECLARE_GL_FUNC(PFNGLDRAWBUFFERSPROC, glDrawBuffers);



int initOpenGL();